apiVersion: v1
kind: Template
metadata:
  name: broker-skeleton
objects:

- apiVersion: servicecatalog.k8s.io/v1beta1
  kind: ClusterServiceBroker
  metadata:
    name: broker-skeleton
  spec:
    url: http://broker-skeleton.broker-skeleton.svc.cluster.local

- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: broker-skeleton

- kind: Service
  apiVersion: v1
  metadata:
    name: broker-skeleton
    labels:
      app: broker-skeleton
  spec:
    selector:
      app: broker-skeleton
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: broker-skeleton
  labels:
    app: broker-skeleton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-skeleton
  template:
    metadata:
      labels:
        app: broker-skeleton
    spec:
      containers:
      - name: service-broker-skeleton
        image: $(IMAGE)
        imagePullPolicy: Never
        command:
        - /opt/servicebroker/servicebroker
        args:
        - --port
        - "8080"
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2

parameters:
- description: Name of the image to use
  displayName: Image name
  name: IMAGE
  required: true
  value: osb-skeleton/servicebroker:latest
